config/routes.rb
Rails.application.routes.draw do
  resources :phones
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: %i[ show edit update destroy ]

  # GET /phones or /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1 or /phones/1.json
  def show
    HardWorker.perform_at(1.minutes, "Faigy", 5)

    render json: @phone
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones or /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: "Phone was successfully created." }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1 or /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: "Phone was successfully updated." }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1 or /phones/1.json
  def destroy
    @phone.destroy!

    respond_to do |format|
      format.html { redirect_to phones_path, status: :see_other, notice: "Phone was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def phone_params
      params.expect(phone: [ :model, :price ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Phone Api" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phones/_form.html.erb
<%= form_with(model: phone) do |form| %>
  <% if phone.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
        <% phone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/phones/_phone.html.erb
<div id="<%= dom_id phone %>">
  <p>
    <strong>Model:</strong>
    <%= phone.model %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= phone.price %>
  </p>

</div>

app/views/phones/edit.html.erb
<% content_for :title, "Editing phone" %>

<h1>Editing phone</h1>

<%= render "form", phone: @phone %>

<br>

<div>
  <%= link_to "Show this phone", @phone %> |
  <%= link_to "Back to phones", phones_path %>
</div>

app/views/phones/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Phones" %>

<h1>Phones</h1>

<div id="phones">
  <% @phones.each do |phone| %>
    <%= render phone %>
    <p>
      <%= link_to "Show this phone", phone %>
    </p>
  <% end %>
</div>

<%= link_to "New phone", new_phone_path %>

app/views/phones/new.html.erb
<% content_for :title, "New phone" %>

<h1>New phone</h1>

<%= render "form", phone: @phone %>

<br>

<div>
  <%= link_to "Back to phones", phones_path %>
</div>

app/views/phones/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @phone %>

<div>
  <%= link_to "Edit this phone", edit_phone_path(@phone) %> |
  <%= link_to "Back to phones", phones_path %>

  <%= button_to "Destroy this phone", @phone, method: :delete %>
</div>